### ISSUE TITLE
[question] What's the usage of BlitzFactor?

### ISSUE THREAD

**Issue by liaodalin19903** [D0rkKnight/BlitzFactor#14]
Hi,

What's the usage of `BlitzFactor`，there is no details in the README.md.

**Comment by shouhanzen** [comment]
It's an old project of mines where I was experimenting with creating a drag n drop UI for editing/refactoring code. It never got to a working point though.

**Comment by liaodalin19903** [comment]
Wow, I'm interest in your  project of `drag n drop UI for editing/refactoring code`, do you think your idea can be realized?

**Comment by shouhanzen** [comment]
Yeah, I think there's some promise here. There's some technical challenges related.

You want to do something with the idea?

**Comment by liaodalin19903** [comment]
I firmly believe that it can be achieved, but there is a saying: No Silver Bullet 
So it's interesting to know if your practice is doing what you want it to.

**Comment by shouhanzen** [comment]
Last I left off, I was able to decompose existing code into scratch-style drag and drop blocks and could also move them around.

Also had some basic refactoring actions available that you could access through a command wheel. Ended up becoming busy with other work.

Largest technical hurdle was calling the refactoring actions from the underlying language server. If you ever end up doing a similar thing, I'd recommend avoiding doing it a VSCode extension. The electron environment is pretty unfriendly towards Treesitter which is used to parse the AST from the code.

So it's probably 30% of the way there if you're curious.
